# Generated by Django 2.1 on 2018-12-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_agregados', models.IntegerField(blank=True, null=True)),
                ('total_presupuestado', models.IntegerField(blank=True, null=True)),
                ('total_real', models.IntegerField(blank=True, null=True)),
                ('total_final', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_presupuestado', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_real', models.PositiveIntegerField(blank=True, null=True)),
                ('comprado', models.BooleanField(default=False)),
                ('lista', models.ForeignKey(default='lista', on_delete=django.db.models.deletion.CASCADE, to='compra.Lista')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.Tienda')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.Lista'),
        ),
    ]
