# Generated by Django 2.1 on 2018-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prolista',
            name='costo_real',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
